### ISSUE TITLE
Make jamjs packaging

### ISSUE THREAD

**Issue by Mikhus** [Mikhus/canv-gauge#17]
Update Readme file, use markdown syntax.
Add packaging stuff to make possibility publish Canv-Gauge via jamjs.org

**Comment by thegounet** [comment]
I think you should package your project to [Bower ](http://bower.io/docs/creating-packages/#register)

I open an issue to angular-canvas-gauge for the same. 
I think your work is interesting for frontend developpers

**Comment by Mikhus** [comment]
Using bower now, as suggested. closing
