### ISSUE TITLE
Canvas-Gauge

### ISSUE THREAD

**Issue by nttu10411206** [Mikhus/canv-gauge#272]
I'm new with coding and I don't know what is going wrong can someone help me?
![code1](https://github.com/Mikhus/canvas-gauges/assets/36870536/efa11e63-de31-4e78-8e3a-f0e2ecc5e1f2)
![code2](https://github.com/Mikhus/canvas-gauges/assets/36870536/c7a40b96-365b-4e17-aa0b-9416259b1a9a)
![error](https://github.com/Mikhus/canvas-gauges/assets/36870536/40181741-dc85-4356-a6e9-0a1b38b2faa7)

**Comment by TuShen121** [comment]
您的邮件我已收到，谢谢！
