### ISSUE TITLE
probleme pour passer des valeurs

### ISSUE THREAD

**Issue by remi11** [Mikhus/canv-gauge#30]
bonsoir,
je voudrais afficher dans une gauge une valeur issue  d'un programme python. Je ne sais pas comment faire. 
pouvez vous m'aider ?

**Comment by Mikhus** [comment]
As I understand you are running python on server side, but gauge is running on client-side (browser) so you have to get the value on client through an HTTP from server and then update it... Depending on your architecture you can use polling or websockets, for example, to request the server for the values... Hope this helps.
