### ISSUE TITLE
On updateConfig gauge with negative values spins like crazy

### ISSUE THREAD

**Issue by ogarcia** [Mikhus/canv-gauge#34]
Imagine that you have:

```js
var tempGauge = new Gauge({
        renderTo: 'temp-gauge',
        width: 380,
        height: 380,
        glow: true,
        units: '°C',
        title: 'Temperature',
        minValue: -10,
        maxValue: 50,
        majorTicks: [ -10, 0, 10, 20, 30, 40, 50 ],
        minorTicks: 10,
        strokeTicks: false,
        highlights: [
          { from: -10, to: 0, color: 'rgba(0, 0, 255, .3)' },
          { from: 0, to: 10, color: 'rgba(0, 0, 255, .1)' },
          { from: 30, to: 35, color: 'rgba(255, 255, 0, .3)' },
          { from: 35, to: 50, color: 'rgba(255, 0, 0, .3)' }
        ],
        colors: {
          plate: '#f5f5f5',
          majorTicks: '#666',
          minorTicks: '#888',
          title: '#444',
          units: '#000',
          numbers: '#222',
          needle: {
            start: 'rgba(240, 128, 128, 2)',
            end: 'rgba(255, 160, 122, .9)'
          }
        },
        animation: {
          delay : 25,
          duration: 500,
          fn : 'linear'
        },
        valueFormat: {
          int: 2,
          dec: 1
        }
});
```

Then initialize and draw (note that the value not is important):
```js
tempGauge.onready = function() {tempGauge.setValue(0);}
tempGauge.draw();
```

If you put some like this:
```js
$(window).resize(function() {
      if ($(window).width() < 1200) {
        tempGauge.updateConfig({ width: 300, height: 300 });
      } else {
        tempGauge.updateConfig({ width: 380, height: 380 });
      }
    });
```

The gauge spins crazy on window resize!!

**Comment by ogarcia** [comment]
The problem not is negative numbers. If the minValue not is zero the gauge spins crazy in window resizes.

**Comment by jason-at-cces** [comment]
I ran into this problem too :(

This is how I worked around it; I called the setValue() function after the resize updateConfig:

        listeners: {
            resize: function (sender, width, height, oldWidth, oldHeight, eOpts) {
                try {
                    if (sender.gaugeObject) {
                        sender.gaugeObject.updateConfig({ width: (width > 0 ? width : 1), height: (height > 0 ? height : 1) });
                        // HACK: Workaround negative min value bug: https://github.com/Mikhus/canv-gauge/issues/34
                        sender.gaugeObject.setValue(sender.getValue());
                    }
                }
                catch (ex) {
                    Ext.log("Gauge Error: " + ex.message);
                }
            }
}

**Comment by Mikhus** [comment]
Actually this fixed with commit https://github.com/Mikhus/canv-gauge/commit/496e7226a2b035e3cb42ac8884695eb618e32d9e

You can check with example-custom-resize.html, provided within.

All kind regards,
Mike
