### ISSUE TITLE
Customization 

### ISSUE THREAD

**Issue by sarfarazengglb** [Mikhus/canv-gauge#37]
I was working with the gauge.I wanted to remove the small gray color display with more visible custom display of numbers.Apart from this looking to change the needle to custom custom pointer.
Can you please advise how can i achieve IT.
![guageexample](https://cloud.githubusercontent.com/assets/6543585/12447597/65fb6f80-bf8a-11e5-98da-8a63eede297f.JPG)

**Comment by Mikhus** [comment]
Hi!

All drawings of the gauge including the needle are hard-coded as far as
drawings implementation is a gauge itself. If you need custom needle look,
you have to re-write it. Currently it only supports color customization,
but not different look. A part of canv-gauge code which draws the needle is
drawNeedle() function, as far as it is open source you can fork and
re-write it to your needs.

Hope this can help.

All kind regards,
Mike

**Comment by dec** [comment]
Hello to all,

I made a pull request with certain additions like new colors and other customization options. Between others, some of the new options allow us to show or hide the value box and text programatically.

I am also writing an Angular 1.x directive based in your excellent code @Mikhus and can be downloadad from anyone interested from here: https://github.com/dec/angular-canvas-gauge

Thanks for cnv-gauge @Mikhus!

**Comment by sarfarazengglb** [comment]
Hi Mykhailo,

Thank Man.Your are the star.I have made the change its working beautifully.
I have not forked it i will do it later. It has been great help as my neck
and my reputation was inline :)
[image: Inline image 1]

*Regards,*

*Mohammed*




On Thu, Jan 21, 2016 at 12:29 PM, Mykhailo Stadnyk <notifications@github.com

**Comment by Mikhus** [comment]
@sarfarazengglb,

Let's give our thanks to amazing work which is actually done by @dec ! That wasn't me.

Best regards,
Mike

**Comment by dec** [comment]
No way! Always thanks you @Mikhus for your excelent piece of code!

P.S. If you need something I can do don't hesitate to contact me or comment here. :)

**Comment by Mikhus** [comment]
@dec , I've added you as a collaborator. Feel free to make your changes. I'd be very appreciate if you have something to update the wiki pages due to your last improvements.

**Comment by dec** [comment]
Thanks @Mikhus! Yes; I want to add the right information in the wiki pages. Just let me some time! :)
