### ISSUE TITLE
Option to skip the constrain to the needle

### ISSUE THREAD

**Issue by highfield** [Mikhus/canv-gauge#40]
It's just a tip to improve the very nice library.
I'm facing the problem to reproduce a compass gauge, and I wanted to make an attempt with your library, first.
Well, I quickly came to a pretty decent result, although there's a problem related to the needle: the constraints. If you were adding an option to skip the needle angle checking (only for the needle angle), you'll have another possibility to offer.
At the moment, I made a modification of the library by myself, by touching the "setValue" and the "drawNeedle" functions.
Here is my result:
![image](https://cloud.githubusercontent.com/assets/2127695/12971392/0b560b0e-d09b-11e5-9a2a-ef6ca6e496b8.png)

**Comment by Mikhus** [comment]
Please, take a look at what was done with commit https://github.com/Mikhus/canv-gauge/commit/c6a457bb27e416bc07e689125658e990cf656fa2
Please, checkout an example.html and example-html.html files. 
I hope there would be everything you need to reach your goals.

In a few words, I added the possibility to configure needle view and the ticks view (now ticksAngle and startAngle options are availabe, using which you can draw ticks on the entire circle or it's part specified by a ticksAngle)

Hope this helps,
Mike
