### ISSUE TITLE
"copy" gauge

### ISSUE THREAD

**Issue by fohnbit** [Mikhus/canv-gauge#44]
Hello,

is it possible in javascript to copy a gauge?
I will try to display 100 gauges ... but will not write for all the same code, to optimize loading time.

gaugeCurrent1.draw();
gaugeCurrent2 = jQuery.extend(true, {}, gaugeCurrent1);
gaugeCurrent2.renderTo = "gauge-Current2";
gaugeCurrent2.draw();

This will not work ... all the gauges should has same layout .. only title and renderTo are different.

Thank you!

**Comment by Mikhus** [comment]
Gauge is drawn on a canvas. Gauge is not a simple JS object but the functionality.
