### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by alsze** [Mikhus/canv-gauge#48]
Just realised that canv-gauge does not seem to support retina screens. Anyone have a fix for this? thanks

**Comment by Mikhus** [comment]
What the exact issue do you have on retina screens? Any screenshots appreciated.

**Comment by alsze** [comment]
thanks for the quick reply. it is just blurry. The right pie is svg and its sharp. There are posts of people adding these devicepixelration scaling code in to standard canvas but not sure how to apply it to the gauge to make it work. hope u can help. thanks

<img width="456" alt="screen shot 2016-08-15 at 9 47 20 pm" src="https://cloud.githubusercontent.com/assets/2231399/17663628/42582b4a-6331-11e6-8732-a94d23e84f0a.png">

**Comment by Mikhus** [comment]
Yeah, seems I figured the problem, hope will be able to post solution soon...

**Comment by Mikhus** [comment]
Hope it should be fine now starting with v1.0.3

**Comment by alsze** [comment]
Ah brilliant. Very nice now. Thank you so much Mikhus. Cheers...
